language: java
before_install:
- chmod +x .buildscript/deploy_snapshot.sh
after_success:
- ".buildscript/deploy_snapshot.sh"
notifications:
  email: false
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - "$HOME/.m2/io"
  - "$HOME/.m2/org"
env:
  global:
  - secure: elVniBqisDQgH6JJb/2t2PLxthjfMH9UiJpkQzn0KAFkCW5OzqhR36T2xeaeP+s4lgCmFKRojr7vcT0zOU4BvtS4wyrUJf971UJ/XWJYyCfR21xWwjeBuvIR8nsx2+r+TDz2hwfLfJ0GsVkaxxu63wegA5qjmfZGUlwC3tCwQWY=
  - secure: Fq+HfYIx3+tJcuL+O4hoyChrb8ri4Kbmu7qE+TSw/Hpq8g/a6VMXb9pca72MCdh1Ucb/94R6ISk8pfPL1IBB9aFgqhahQgArGkD9mV4UcpPFyB2OwchT0G7eceO2oMPG/kyL6hM4/nkIqUCrrNT0MFvPD/b6iwzDzEnuXNmOGyk=
